baseurl: "https://strobo.fm"
title: "strobo.fm"
footnotereturnlinkcontents: "↩"
contentdir: "content"
layoutdir: "layout"
staticdir: "static"
publishdir: "public"
uglyURLs: false
metaDataFormat: "yaml"
languageCode: "ja"
permalinks:
  post: "/:title"
