baseurl: "https://strobo.fm"
title: "#strobofm"
footnotereturnlinkcontents: "↩"
contentdir: "content"
layoutdir: "layout"
staticdir: "static"
publishdir: "public"
uglyURLs: false
metaDataFormat: "yaml"
languageCode: "ja"
permalinks:
  post: "/:title"
taxonomies:
  people: "people"
params:
  StaticURL: "https://chtbl.com/track/GG45GF/strobofm.netlify.app"
markup:
  goldmark:
    renderer:
      unsafe: true
