baseurl: "https://strobo.fm"
title: "strobo.fm"
footnotereturnlinkcontents: "↩"
contentdir: "content"
layoutdir: "layout"
staticdir: "static"
publishdir: "docs"
uglyURLs: false
metaDataFormat: "yaml"
params:
  android: http://subscribeonandroid.com/strobo.fm/index.xml
  feed: https://strobo.fm/index.xml
permalinks:
  post: "/:title"
